image: gradle:8.5.0-jdk21-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  # GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - compile
  - checkstyle
  - test
  - coverageReport
  - triage

compile:
  stage: compile
  script:
    - ./gradlew assemble

#checkstyle:
#  stage: checkstyle
#  parallel: 2
#  script:
#    - ./gradlew checkstyleMain
#    - ./gradlew checkstyleTest

checkstyle:
  stage: checkstyle
  needs: []
  script:
    - ./gradlew $CHECKSTYLE
  parallel:
    matrix:
      - CHECKSTYLE: ['checkstyleMain', 'checkstyleTest']

commons:test:
  stage: test
  needs:
    - compile
  script:
    - ./gradlew :commons:test --tests commons.$TEST_CLASS
  parallel:
    matrix:
      - TEST_CLASS:
        - "ColourTest"
        - "CurrencyTest"
        - "EventTest"
        - "ExpenseTest"
        - "PaymentTest"
        - "PersonTest"
        - "TagTest"

client:test:
  stage: test
  needs:
    - compile
  script:
    - ./gradlew :client:test --tests client.scenes.$TEST_CLASS
  parallel:
    matrix:
      - TEST_CLASS:
          - "MainCtrlTest"

server:database:test:
  stage: test
  needs:
    - compile
  script:
    - ./gradlew :server:test --tests server.database.$TEST_CLASS
  parallel:
    matrix:
      - TEST_CLASS:
          - "ColourRepositoryTest"
          - "CurrencyRepositoryTest"
          - "EventRepositoryTest"
          - "ExpenseRepositoryTest"
          - "PaymentRepositoryTest"
          - "PersonRepositoryTest"
          - "TagRepositoryTest"

server:service:test:
  stage: test
  needs:
    - compile
  script:
    - ./gradlew :server:test --tests server.service.$TEST_CLASS
  parallel:
    matrix:
      - TEST_CLASS:
          - "PersonServiceTest"
          - "PaymentServiceTest"
          - "ExpenseServiceTest"

server:controller:test:
  stage: test
  needs:
    - compile
  script:
    - ./gradlew :server:test --tests server.api.$TEST_CLASS
  parallel:
    matrix:
      - TEST_CLASS:
          - "PersonControllerTest"
          - "PaymentControllerTest"
          - "ExpenseControllerTest"

coverageReport:
  stage: coverageReport
  allow_failure: true
  needs: []
#    - commons:test
#    - client:test
#    - server:database:test
#    - server:service:test
#    - server:controller:test
  script:
    - ./gradlew compileTestJava
    - ./gradlew AggregateJacocoReport
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/

dry-run:triage:
  image: ruby:3.0
  stage: triage
  needs: []
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH --debug
  when: manual
  except:
    - schedules

run:triage:
  image: ruby:3.0
  stage: triage
  needs: []
  script:
    - gem install gitlab-triage
    - gitlab-triage --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH
  coverage: /TestCoverage:(\d+)%/
