image: gradle:8.5.0-jdk21-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - compile
  - checkstyle
  - test

compile:
  stage: compile
  script:
    - ./gradlew assemble

checkstyle:
  stage: checkstyle
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew AggregateJacocoReport
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/
