image: gradle:8.5.0-jdk21-alpine

stages:
  - checkstyle
  - build
  - triage

checkstyle:
  stage: checkstyle
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest

build:
  stage: build
  needs:
    - checkstyle
  script:
    - apk update
    - apk add xvfb-run
    - apk add gtk+3.0
    - ./gradlew --build-cache assemble
    - ./gradlew --build-cache bootrun --args='--seed' &   # Start the server as a background process
    - sleep 15  # Adjust the sleep time based on how long it takes for the server to start
    - xvfb-run ./gradlew --build-cache :client:test
    - ./gradlew --build-cache test
    - ./gradlew --build-cache compileTestJava
    - ./gradlew --build-cache AggregateJacocoReport
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/

dry-run:triage:
  image: ruby:3.0
  stage: triage
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH --debug
  when: manual
  except:
    - schedules

run:triage:
  image: ruby:3.0
  stage: triage
  script:
    - gem install gitlab-triage
    - gitlab-triage --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH
