image: gradle:8.5.0-jdk21-alpine

stages:
  - compile
  - checkstyle
  - test
  - coverageReport
  - triage

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: "$CI_COMMIT_SHA"
  policy: pull-push
  paths:
    - build
    - "*/build"
    - .gradle

compile:
  stage: compile
  script:
    - ./gradlew --build-cache assemble

checkstyle:
  stage: checkstyle
  needs:
    - compile
  script:
    - ./gradlew --build-cache checkstyleMain
    - ./gradlew --build-cache checkstyleTest

commons:test:
  stage: test
  needs:
    - checkstyle
  script:
    - ./gradlew --build-cache :commons:test

server:test:
  stage: test
  needs:
    - commons:test
  script:
    - ./gradlew --build-cache :server:test

client:test:
  stage: test
  needs:
    - server:test
  before_script:
    - apk update
    - apk add xvfb-run
    - apk add gtk+3.0
    - ./gradlew --build-cache bootrun --args='--seed' &   # Start the server as a background process
    - sleep 30  # Adjust the sleep time based on how long it takes for the server to start
  script:
    - xvfb-run ./gradlew --build-cache :client:test

coverageReport:
  stage: coverageReport
  needs:
    - client:test
  script:
    - ./gradlew --build-cache compileTestJava
    - ./gradlew --build-cache AggregateJacocoReport
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/

dry-run:triage:
  image: ruby:3.0
  stage: triage
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH --debug
  when: manual
  except:
    - schedules

run:triage:
  image: ruby:3.0
  stage: triage
  script:
    - gem install gitlab-triage
    - gitlab-triage --token j4Sr_UUUmsJ96xkkbs4y --host-url $CI_SERVER_URL --source projects --source-id $CI_PROJECT_PATH
