resource_rules:
  issues:
    rules:
      - name: Ensure new issues have a state label
        conditions:
          forbidden_labels:
            - state::idea
            - state::preparation
            - state::in-progress
            - state::feedback
            - state::completed
            - state::aborted
            - state::blocked
        actions:
          labels:
            - state::idea

      - name: Ensure new issues have a priority label
        conditions:
          forbidden_labels:
            - priority::low
            - priority::normal
            - priority::high
            - priority::urgent
        actions:
          labels:
            - priority::normal

      - name: Ensure closed issues that don't have a state::aborted/completed label will get the state::completed label
        conditions:
          state: closed
          forbidden_labels:
            - state::completed
            - state::aborted
        actions:
          labels:
            - state::completed

  merge_requests:
    rules:
      - name: Ensure all non-draft open merge requests have the state::feedback label
        conditions:
          state: opened
          draft: false
          forbidden_labels:
            - state::feedback
        actions:
          labels:
            - state::feedback
      - name: Give all draft merge requests the state::in-progress label
        conditions:
          state: opened
          draft: true
          forbidden_labels:
            - state::in-progress
            - state::preparation
            - state::idea
        actions:
          labels:
            - state::in-progress
      - name: Ensures closed merge request have a correct label
        conditions:
          state: closed
          forbidden_labels:
            - state::aborted
        actions:
          labels:
            - state::aborted
      - name: Ensures merged merge request have a correct label
        conditions:
          state: merged
          forbidden_labels:
            - state::completed
        actions:
          labels:
            - state::completed
      - name: Ensure a priority label is present
        conditions:
          forbidden_labels:
            - priority::low
            - priority::normal
            - priority::high
            - priority::urgent
        actions:
          labels:
            - priority::normal